name: CMake Build (Ubuntu aarch64)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Upgrade system
      shell: bash
      working-directory: ${{runner.workspace}}
      run: |
        sudo apt update
        sudo apt upgrade
    - name: Install dependencies
      shell: bash
      working-directory: ${{runner.workspace}}
      run: |
        sudo apt install {gcc-10,g++-10,pkg-config}-aarch64-linux-gnu libsdl2-dev:arm64 qtbase5-dev:arm64 libslirp-dev:arm64 libarchive-dev:arm64 libepoxy-dev:arm64
    - name: Create build environment
      run: mkdir ${{runner.workspace}}/build
    - name: Configure
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: |
          CC=aarch64-linux-gnu-gcc-10 CXX=aarch64-linux-gnu-g++-10 cmake -DPKG_CONFIG_EXECUTABLE=/usr/bin/aarch64-linux-gnu-pkg-config $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - name: Make
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: |
        make -j$(nproc --all) \
        && mkdir dist \
        && cp melonDS dist
    - uses: actions/upload-artifact@v1
      with:
        name: melonDS-ubuntu-aarch64
        path: ${{runner.workspace}}/build/dist
